name: CodinGoat_flutter
description: A login widget with login/signup functionalities to help speed up development
version: 5.0.0
repository: https://github.com/NearHuscarl/flutter_login

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies: 
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.0.0
  intl_phone_number_input: ^0.7.4
  phone_numbers_parser: ^8.0.0
  provider: ^6.0.1
  quiver: ^3.0.1
  sign_in_button: ^3.0.0
  url_launcher: ^6.1.3
  intl: ^0.19.0
  stylish_bottom_bar: ^1.1.0
  another_flushbar: ^1.10.29
  another_transformer_page_view: ^2.0.0
  multi_dropdown: ^2.1.4
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  mockito: ^5.0.16

flutter:
  uses-material-design: true
  assets:
    - assets/images/ecorp.png
    - assets/images/bg_login.jpg
    - assets/images/logo_cart.png
    - assets/images/cg_logo.png
    - assets/images/shoe.jpg
    - assets/images/car.jpg
    - assets/images/bike.jpg
    - assets/images/mobile.jpg
    - assets/images/property.jpg
    - assets/images/ad_bg.png
    - assets/images/nike_shoe.png
    - assets/images/mobile1.jpg
    - assets/images/mobile2.jpg
    - assets/images/mobile3.jpg



  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/SourceSansPro-ExtraLightItalic.ttf
          weight: 200
        - asset: assets/fonts/SourceSansPro-Light.ttf
          weight: 300
        - asset: assets/fonts/SourceSansPro-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/SourceSansPro-Regular.ttf
        - asset: assets/fonts/SourceSansPro-Italic.ttf
          style: italic
        - asset: assets/fonts/SourceSansPro-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/SourceSansPro-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/SourceSansPro-Bold.ttf
          weight: 700
        - asset: assets/fonts/SourceSansPro-BoldItalic.ttf
          weight: 700
          style: italic
    - family: NotoSans
      fonts:
        - asset: assets/fonts/NotoSans-Regular.ttf
        - asset: assets/fonts/NotoSans-Italic.ttf
          style: italic
        - asset: assets/fonts/NotoSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/NotoSans-BoldItalic.ttf
          weight: 700
          style: italic
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Light.ttf
          weight: 300
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
          weight: 500
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Quicksand-Bold.ttf
          weight: 700
